In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("Resources/Aggregated_Metrics_By_Country_And_Subscriber_Status.csv")
df1

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,HK,True,23,1,0,0,2,0,0.671870,39.640348,0
1,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,ME,True,3,0,0,0,0,0,0.498870,29.433333,0
2,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,RW,True,2,0,0,0,0,0,0.681780,40.225000,0
3,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,US,True,979,81,6,8,16,4,0.694854,40.996389,0
4,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,DE,False,75,3,0,1,0,0,0.661515,39.029373,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55287,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MM,False,1,0,0,0,0,0,0.622642,33.000000,0
55288,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SA,True,14,1,0,0,0,0,0.515569,27.325143,0
55289,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,DZ,False,2,0,0,0,0,0,0.782075,41.450000,0
55290,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MX,False,11,0,0,0,0,0,0.636178,33.717455,0
55291,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SR,True,1,0,0,0,0,0,0.985679,52.241000,0

In [3]:
df2 = pd.read_csv("Resources/Aggregated_Metrics_By_Video.csv")
df2

,Video,Video title,Video pubÂ­lish time,ComÂ­ments adÂ­ded,Shares,DisÂ­likes,Likes,SubÂ­scribers lost,SubÂ­scribers gained,RPM (USD),CPM (USD),AvÂ­erÂ­age perÂ­centÂ­age viewed (%),AvÂ­erÂ­age view durÂ­aÂ­tion,Views,Watch time (hours),SubÂ­scribers,Your esÂ­timÂ­ated revÂ­enÂ­ue (USD),ImÂ­presÂ­sions,ImÂ­presÂ­sions click-through rate (%)
0,Total,NaN,NaN,14197,39640,3902,225021,45790,229241,5.276,11.990,26.61,0:03:25,5568487,317602.3536,183451,29068.652,100954064,3.16
1,4OZip0cgOho,How I Would Learn Data Science (If I Had to St...,"May 8, 2020",907,9583,942,46903,451,46904,6.353,12.835,36.65,0:03:09,1253559,65850.7042,46453,7959.533,26498799,3.14
2,78LjdAAw0wA,100K Channel Update + AMA Stream!,"Nov 12, 2020",412,4,4,130,15,12,2.668,6.259,6.26,0:05:14,2291,200.2966,-3,6.113,188318,0.72
3,hO_YKK_0Qck,Uber Driver to Machine Learning Engineer in 9 ...,"Jul 16, 2020",402,152,15,881,9,198,9.516,11.695,15.12,0:10:21,21350,3687.3387,189,202.963,442334,2.53
4,uXLnbdHMf8w,Why I'm Starting Data Science Over Again.,"Aug 29, 2020",375,367,22,2622,40,1957,3.143,7.943,33.41,0:02:36,49564,2148.3110,1917,155.779,521185,4.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,FBgs-BSTIJE,Demystifying Data Science Roles,"Nov 30, 2018",3,5,1,48,1,8,5.218,16.232,55.55,0:03:28,978,56.5930,7,5.103,26202,2.24
220,Yr5T3T4tq-g,Most Data Science Hopefuls Overlook This Impor...,"May 25, 2019",3,0,0,44,0,5,3.374,15.596,58.62,0:02:06,548,19.2752,5,1.849,21780,1.61
221,j-Z-je6K4Yg,IT'S NOT TOO LATE TO LEARN CODE!,"Dec 18, 2018",3,1,0,35,0,7,3.784,12.590,60.52,0:01:52,721,22.5450,7,2.728,18635,2.65
222,5jntoZX-Tc8,NASA Physicist Turned Data Scientist (Tim Bowl...,"May 5, 2019",2,5,0,38,0,3,2.651,12.206,16.93,0:03:09,1094,57.6363,3,2.900,34642,1.99
223,5p73cIRYCZg,ProjectDemoCSC478_UFCFightData,"Jun 6, 2017",0,2,0,1,0,0,0.050,NaN,8.79,0:01:04,60,1.0684,0,0.003,365,11.51

In [4]:
df3 = pd.read_csv("Resources/All_Comments_Final.csv")
df3

,Comments,Comment_ID,Reply_Count,Like_Count,Date,VidId,user_ID
0,Thanks for this video Ken.\n\nI decided to go ...,UgxFZTIzC4UPyhhX_PZ4AaABAg,0,0,2022-01-22T08:13:29Z,xpIFS6jZbe8,user_981
1,Hello ken jee!!! I'm doing a graduation on Com...,Ugx3IYuAufhb932GYQx4AaABAg,0,0,2022-01-22T01:09:46Z,xpIFS6jZbe8,user_213
2,"Thanks for this video, man. So useful. I'll me...",UgyhwwoK24arzRt1mud4AaABAg,0,0,2022-01-21T23:59:05Z,rEWPqw6rMGI,user_1065
3,Great video!!! I started learning Python 8 mon...,UgwrrI7nd3WClsotmHV4AaABAg,0,0,2022-01-21T23:00:37Z,xpIFS6jZbe8,user_3391
4,Been watching hours of your material (and Tina...,UgxlOrHO4MHKSwY9mUN4AaABAg,0,0,2022-01-21T20:24:20Z,sHRq-LshG3U,user_2816
...,...,...,...,...,...,...,...
10235,"Dear Ken,\nMay I know how the input data with ...",UgzX5v48CJAPbvynwTR4AaABAg,1,0,2018-07-06T07:08:39Z,qfRhKHV8-t4,user_5850
10236,What's your prediction Ken for 2018 or at leas...,UgwdI9ydb2nk-FIJ1sN4AaABAg,0,0,2018-05-15T00:01:12Z,qfRhKHV8-t4,user_2676
10237,Nice. I have some nice models for this doing v...,UgyTi5fEIpZBoED9Fc94AaABAg,0,0,2018-05-04T20:58:54Z,qfRhKHV8-t4,user_4533
10238,Great video! Can you please post the github li...,UgyhJTCKn88b0lggR794AaABAg,0,0,2018-02-20T16:46:19Z,qfRhKHV8-t4,user_3368
10239,Hi Ken\n\nI've been researching about this. Wo...,UgzG1dz-KieX_gxjMWd4AaABAg,6,2,2017-12-03T18:52:35Z,qfRhKHV8-t4,user_5345

In [5]:
df4 = pd.read_csv("Resources/Video_Performance_Over_Time.csv")
df4

,Date,Video Title,External Video ID,Video Length,Thumbnail link,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,19 Jan 2022,Kaggle Project From Scratch - Part 2 (Explorat...,KQ80oD_boBM,2191,https://i.ytimg.com/vi/KQ80oD_boBM/hqdefault.jpg,13,0,0,0,0,0,0.069055,151.300154,0
1,19 Jan 2022,Welcome To My Channel | Ken Jee | Data Science,smeFkHwnM_k,51,https://i.ytimg.com/vi/smeFkHwnM_k/hqdefault.jpg,2,0,0,0,1,0,0.471255,24.034000,0
2,19 Jan 2022,How She Dominated the FAANG Data Science Inter...,vfV4nm004VQ,2686,https://i.ytimg.com/vi/vfV4nm004VQ/hqdefault.jpg,10,0,0,0,0,0,0.126049,338.567500,0
3,19 Jan 2022,The 9 Books That Changed My Perspective in 2019,3TrAYmrmA8o,980,https://i.ytimg.com/vi/3TrAYmrmA8o/hqdefault.jpg,1,0,0,0,0,0,0.011508,11.278000,0
4,19 Jan 2022,Interview with the Director of AI Research @ N...,Xgg7dIKys9E,2904,https://i.ytimg.com/vi/Xgg7dIKys9E/hqdefault.jpg,1,0,0,0,0,0,0.007541,21.900000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111852,21 Nov 2017,Predicting Crypto-Currency Price Using RNN lST...,qfRhKHV8-t4,311,https://i.ytimg.com/vi/qfRhKHV8-t4/hqdefault.jpg,2,0,0,0,0,0,0.693108,215.556500,0
111853,20 Nov 2017,Predicting Crypto-Currency Price Using RNN lST...,qfRhKHV8-t4,311,https://i.ytimg.com/vi/qfRhKHV8-t4/hqdefault.jpg,9,0,0,0,0,0,0.492501,153.167667,0
111854,19 Nov 2017,Predicting Crypto-Currency Price Using RNN lST...,qfRhKHV8-t4,311,https://i.ytimg.com/vi/qfRhKHV8-t4/hqdefault.jpg,4,0,0,0,0,0,0.087268,27.140250,0
111855,18 Nov 2017,Predicting Crypto-Currency Price Using RNN lST...,qfRhKHV8-t4,311,https://i.ytimg.com/vi/qfRhKHV8-t4/hqdefault.jpg,13,0,0,0,0,0,0.444176,138.138769,0
111856,1 Nov 2017,ProjectDemoCSC478_UFCFightData,5p73cIRYCZg,729,https://i.ytimg.com/vi/5p73cIRYCZg/hqdefault.jpg,1,0,0,0,0,0,0.003018,2.200000,0